name: wsbd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - opencv
  - pillow
  - sahi=0.11.22
  - albumentations=1.3.1
  - pip
  - pandas=2.0.3
  - pip:
    - mmengine==0.10.7
    - mmcv==2.1.0
    